[package]
name = "cst"
version = "0.1.101"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substring = "1"
walkdir = "2"

[dev-dependencies]
rand = "0.8"